
services:
  minimalapitemplate.api:
    image: ${DOCKER_REGISTRY-}minimalapitemplate.api
    container_name: minimalapitemplate.api
    environment:
      - MassTransit__PublishEnabled=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=
      - SEQ_SERVER_URL=http://host.docker.internal:8903
    ports:
      - "8901:443"
    networks:
      - shared-network
    depends_on:
      minimalapitemplate.cache:
        condition: service_started
      minimalapitemplate.seq:
        condition: service_started
      minimalapitemplate.rabbit:
        condition: service_started
      minimalapitemplate.keycloak:
        condition: service_started
      minimalapitemplate.db:
        condition: service_healthy
    build:
      context: .
      dockerfile: src/MinimalApiTemplate.Api/Dockerfile

  minimalapitemplate.worker:
    image: ${DOCKER_REGISTRY-}minimalapitemplate.worker
    container_name: minimalapitemplate.worker
    environment:
      - MassTransit__ConsumerEnabled=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=
      - SEQ_SERVER_URL=http://host.docker.internal:8903
    ports:
      - "8910:80"
    networks:
      - shared-network
    depends_on:
      minimalapitemplate.seq:
        condition: service_started
      minimalapitemplate.rabbit:
        condition: service_started
    build:
      context: .
      dockerfile: src/MinimalApiTemplate.Worker/Dockerfile

  minimalapitemplate.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: minimalapitemplate.db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=61tagstdgdtfsgkF!@
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "61tagstdgdtfsgkF!@", "-Q", "SELECT 1"]
      interval: 5s
      timeout: 3s
      retries: 10   
    ports:
      - "8902:1433"
    networks:
      - shared-network
  
  minimalapitemplate.seq:
    image: datalust/seq
    container_name: minimalapitemplate.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8903:80"
    volumes:
      - seq_data:/data
    networks:
      - shared-network

  minimalapitemplate.cache:
    image: redis
    container_name: minimalapitemplate.cache
    ports:
      - "8904:6379"
    networks:
      - shared-network

  minimalapitemplate.rabbit:
    image: rabbitmq:3-management
    container_name: minimalapitemplate.rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "8905:15672"
      - "8906:5672"
    networks:
      - shared-network

  minimalapitemplate.grafana:
    image: grafana/grafana
    container_name: minimalapitemplate.grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/etc/grafana
      - grafana_dashboards:/var/lib/grafana/dashboards
      - grafana_certs:/certs
    networks:
      - shared-network

  minimalapitemplate.prometheus:
    image: prom/prometheus
    container_name: minimalapitemplate.prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./scripts/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - shared-network

  minimalapitemplate.keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: minimalapitemplate.keycloak
    command: start-dev --log-level=INFO --features=preview
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=minimalapitemplate.keycloak.db
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=secret
      - KC_TRANSACTION_XA_ENABLED=false
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true 
      - KC_HOSTNAME_URL=http://minimalapitemplate.keycloak
      - KC_HOSTNAME_ADMIN_URL=http://minimalapitemplate.keycloak
    ports:
      - "8930:8080"
    healthcheck:
      test: ["CMD-SHELL", "exec 3<> /dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\\r\\nhost: http://localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3; if [ $? -eq 0 ]; then echo 'Healthcheck Successful'; exit 0; else echo 'Healthcheck Failed'; exit 1; fi;"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    depends_on:
      minimalapitemplate.keycloak.db:
        condition: service_healthy
    networks:
     - shared-network
 
  minimalapitemplate.keycloak.cli:
    image: "quay.io/adorsys/keycloak-config-cli:latest-26"
    container_name: minimalapitemplate.keycloak.cli
    command:
      - "java"
      - "-jar"
      - "./target/keycloak-config-cli.jar"
      - "--keycloak.url=http://minimalapitemplate.keycloak:8080"
      - "--keycloak.ssl-verify=true"
      - "--keycloak.user=admin"
      - "--keycloak.password=admin"
      - "--import.files.locations=/import-data/*"
    networks:
      - shared-network
    volumes:
      - "./scripts/keycloak/realm-export.json:/import-data/realm-export.json"
    depends_on:
      minimalapitemplate.keycloak:
        condition: service_healthy

  minimalapitemplate.keycloak.db:
    image: postgres:17
    container_name: minimalapitemplate.keycloak.db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared-network
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  seq_data:
  grafana_data:
  grafana_dashboards:
  grafana_certs:
  prometheus_data:
  pg_data:

networks:
  shared-network:
    driver: bridge