
services:
  minimalapitemplate.api:
    image: ${DOCKER_REGISTRY-}minimalapitemplate.api
    container_name: minimalapitemplate.api
    environment:
      - MassTransit__PublishEnabled=true
    ports:
      - "8901:443"
    networks:
      - shared-network
    depends_on:
      - minimalapitemplate.db
      - minimalapitemplate.cache
      - minimalapitemplate.seq
    build:
      context: .
      dockerfile: src/MinimalApiTemplate.Api/Dockerfile

  minimalapitemplate.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: minimalapitemplate.db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=61tagstdgdtfsgkF!@
    ports:
      - "8902:1433"
    networks:
      - shared-network
  
  minimalapitemplate.seq:
    image: datalust/seq
    container_name: minimalapitemplate.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8903:80"
    volumes:
      - seq_data:/data
    networks:
      - shared-network

  minimalapitemplate.cache:
    image: redis
    container_name: minimalapitemplate.cache
    ports:
      - "8904:6379"
    networks:
      - shared-network

  minimalapitemplate.rabbit:
    image: rabbitmq:3-management
    container_name: minimalapitemplate.rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "8905:15672"
      - "8906:5672"
    networks:
      - shared-network

volumes:
  seq_data:

networks:
  shared-network:
    driver: bridge