global using System.Net;
global using Riok.Mapperly.Abstractions;
global using Mediator;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.OutputCaching;
global using MinimalApiTemplate.Api.Common.Interfaces;
global using FluentValidation;
global using MinimalApiTemplate.Api.Common.Extensions;
global using MinimalApiTemplate.Api.Common.Validation;
global using MinimalApiTemplate.Api.Common.Models.Enums;
global using MinimalApiTemplate.Api.Common.Models;
global using static MinimalApiTemplate.Application.Common.Constants;
global using static MinimalApiTemplate.Api.Common.Constants;