<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
      <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" />
      <PackageReference Include="Aspire.StackExchange.Redis.OutputCaching" />
      <PackageReference Include="Aspire.RabbitMQ.Client" />
      <PackageReference Include="Audit.NET.SqlServer" />
      <PackageReference Include="Rebus.ServiceProvider" />
      <PackageReference Include="Rebus.RabbitMq" />
      <PackageReference Include="Rebus.OpenTelemetry" />
      <PackageReference Include="Microsoft.AspNetCore.HeaderPropagation" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
      <PackageReference Include="OpenTelemetry" />
      <PackageReference Include="Scrutor" />
      <PackageReference Include="Serilog" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Persistence\Migrations\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MinimalApiTemplate.Application\MinimalApiTemplate.Application.csproj" />
      <ProjectReference Include="..\MinimalApiTemplate.Domain\MinimalApiTemplate.Domain.csproj" />
    </ItemGroup>
</Project>
