# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore MinimalApiTemplate.sln
    
    - name: Build
      run: dotnet build MinimalApiTemplate.sln --no-restore
    
    - name: Install Code Coverage Tool
      run: dotnet tool install dotnet-reportgenerator-globaltool --version 4.8.13 --tool-path ${{ github.workspace }}/report-tool/ --no-cache
    
    - name: Test
      run: dotnet test MinimalApiTemplate.sln -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura --no-build --verbosity normal
    
    - name: Compile Code Coverage
      run:  ${{ github.workspace }}/report-tool/reportgenerator -reports:"${{ github.workspace }}/tests/*Tests*/coverage.cobertura.xml" -targetdir:"${{ github.workspace }}/CodeCoverage" -reporttypes:"Cobertura"
    
    - uses: 5monkeys/cobertura-action@master
      with:
        path: "${{ github.workspace }}/CodeCoverage/Cobertura.xml"
        minimum_coverage: 75
